name: sleepnotfound404
description: AI-powered career guidance platform for secondary students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase 2026 Core
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # AI & Environment
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  http: ^1.1.0

  # UI & Utilities
  file_picker: ^10.3.10
  provider: ^6.1.2
  lottie: ^3.3.2
  flutter_spinkit: ^5.2.1
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.7+1
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets for app
  assets:
    - assets/data/

